# opentrons travis configuration

matrix:
  fast_finish: false
  include:
    - os: linux
      sudo: false
      language: python
      python: '3.6'
      # TODO(mc, 2018-10-25): enable api docs on linux after BM's fixup work
      env:
        LINT=true
        BUILD_APP=true
        BUILD_PD=true
        BUILD_COMPONENTS=true
        BUILD_API_DOCS=false
      addons:
        apt:
          sources: &common_sources
          packages: &common_packages
            - g++
            - gcc
            - icnsutils # electron-builder dependency
            - graphicsmagick # electron-builder dependency
            - xvfb

    - os: osx
      language: generic
      if: type != pull_request AND (tag IS present OR branch IN (master, edge))
      env:
        LINT=false
        BUILD_APP=true
        BUILD_PD=false
        BUILD_COMPONENTS=false
        BUILD_API_DOCS=false

cache:
  pip: true
  yarn: true
  directories:
    - $HOME/.pyenv
    - $HOME/Library/Caches/Homebrew

before_install:
  # source these scripts because they modify $PATH
  - source scripts/travis-env.sh
  - source scripts/travis-install.sh

install:
  - make install

script:
  - make test
  - if [[ $LINT = true ]]; then make lint; fi
  - if [[ $BUILD_COMPONENTS = true ]]; then make -C components build; fi
  - if [[ $BUILD_PD = true ]]; then make -C protocol-designer build; fi
  - if [[ $BUILD_APP = true ]]; then make -C app-shell dist-$APP_OS_TARGET; fi
  - if [[ $BUILD_API_DOCS = true ]]; then (make -C api docs > /dev/null); fi

after_success:
  - make coverage

deploy:
  # TODO(mc, 2018-03-25): api docs deploy
  - provider: script
    skip_cleanup: true
    script: echo "not implemented!"
    on:
        condition: $BUILD_API_DOCS = true
        repo: Opentrons/opentrons
        tags: true

  # app deploy
  - provider: s3
    skip_cleanup: true
    # TODO(mc, 2018-03-26): use AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $OT_BUCKET_APP
    upload-dir: $OT_FOLDER_APP
    local-dir: $(pwd)/app-shell/dist/publish
    # TODO(mc, 2018-03-26): use bucket policy
    acl: public_read
    on:
      condition: $BUILD_APP = true
      repo: Opentrons/opentrons
      all_branches: true

  # protocol designer deploy
  - provider: s3
    # TODO(mc, 2018-03-26): use AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: opentrons-protocol-designer
    skip_cleanup: true
    local-dir: $(pwd)/protocol-designer/dist/
    upload-dir: $TRAVIS_BRANCH
    # TODO(mc, 2018-03-26): use bucket policy
    acl: public_read
    # TODO(mc, 2018-03-26): why is this region not default?
    region: us-west-2
    on:
      condition: $BUILD_PD = true
      repo: Opentrons/opentrons
      all_branches: true

  # components library deploy
  - provider: s3
    # TODO(mc, 2018-03-26): use AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: opentrons-components
    skip_cleanup: true
    local-dir: $(pwd)/components/dist/
    upload-dir: $TRAVIS_BRANCH
    # TODO(mc, 2018-03-26): use bucket policy
    acl: public_read
    # TODO(mc, 2018-03-26): why is this region not default?
    region: us-west-2
    on:
      condition: $BUILD_COMPONENTS = true
      repo: Opentrons/opentrons
      all_branches: true

env:
  global:
    - OT_BUILD: $TRAVIS_BUILD_NUMBER
    - OT_BRANCH: $TRAVIS_BRANCH
    - OT_TAG: $TRAVIS_TAG

    - OT_BUCKET_APP: opentrons-run-app
    - OT_FOLDER_APP: builds

    # TODO(mc, 2018-03-25): delete/move these to GH pages deploy as appropriate
    - ENCRYPTION_LABEL: c6cefc96bb2c
    - COMMIT_AUTHOR_EMAIL: sphinx@opentrons.com

notifications:
  email:
    on_success: change
    on_failure: change
